image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 938.63443,    0.     ,  662.61742,
            0.     ,  938.46233,  364.87657,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.132089, -0.248230, 0.005286, 0.008272, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 943.65259,    0.     ,  676.72327,    0.     ,
            0.     ,  960.57623,  367.90011,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]